name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: SSH to server, pull & restart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
            context: .
            file: server/Dockerfile
            tags: amatiasq/mud-proxy:latest

      - name: Push the latest Docker image
        run: docker push amatiasq/mud-proxy:latest

      - name: Pull image from server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull amatiasq/mud-proxy
            docker stop mud-proxy
            docker rm mud-proxy
            docker run -d \
              -p 53472:53472 \
              --restart unless-stopped \
              --name mud-proxy \
              amatiasq/mud-proxy:latest
